import { useEffect, useCallback, useState } from 'react';
import {
  Box,
  Stepper,
  Step,
  StepLabel,
  StepButton,
  Button,
  Typography,
  Paper,
  Chip,
  Tooltip,
  CircularProgress,
} from '@mui/material';
import {
  ArrowBack,
  ArrowForward,
  ShoppingCart,
  Refresh,
  Bookmark,
} from '@mui/icons-material';
import { useFrameWizardStore, TOTAL_STEPS } from '../stores/frameWizardStore';
import { loadAllLibraries } from '../utils/frameLibraryLoader';
import { ObjectiveChangerStep } from './frameWizard/ObjectiveChangerStep';
import { ObjectiveStep } from './frameWizard/ObjectiveStep';
import { IlluminationStep } from './frameWizard/IlluminationStep';
import { FluorescenceStep } from './frameWizard/FluorescenceStep';
import { CameraStep } from './frameWizard/CameraStep';
import { SampleHolderStep } from './frameWizard/SampleHolderStep';
import { SummaryQuoteStep } from './frameWizard/SummaryQuoteStep';
import { FramePreview } from './frameWizard/FramePreview';
import { PresetSelector } from './frameWizard/PresetSelector';

// WP1: new 7-step tab order.
const STEP_LABELS = [
  'Objective Changer',
  'Objectives',
  'Illumination',
  'Fluorescence',
  'Camera',
  'Sample Holders',
  'Summary & Quote',
];

export function FrameWizardPage() {
  const {
    currentStep,
    setStep,
    nextStep,
    prevStep,
    resetWizard,
    setObjectives,
    setLenses,
    setCameras,
    setFluorescenceOptions,
    getTotalPrice,
    getStepPrice,
    getSelectedComponents,
    isLoading,
    setIsLoading,
  } = useFrameWizardStore();

  const [presetOpen, setPresetOpen] = useState(false);

  useEffect(() => {
    setIsLoading(true);
    loadAllLibraries().then(({ objectives, lenses, cameras, fluorescence }) => {
      setObjectives(objectives);
      setLenses(lenses);
      setCameras(cameras);
      setFluorescenceOptions(fluorescence);
      setIsLoading(false);
    });
  }, [setObjectives, setLenses, setCameras, setFluorescenceOptions, setIsLoading]);

  const handleOpenInCanvas = useCallback(() => {
    const components = getSelectedComponents();
    const layout = {
      uc2_components: components.map((c, i) => ({
        name: `${c.moduleId}_${i}`,
        file: '',
        grid_pos: c.gridPos,
        rotation: c.rotation,
        moduleId: c.moduleId,
        originalName: c.moduleId,
        description: '',
        params: c.params || {},
      })),
      annotations: [],
      layers: [{ id: 'layer-0', name: 'Layer 0', index: 0, visible: true }],
      name: 'FRAME Configuration',
      author: '',
      githubAccount: '',
      description: 'Generated by FRAME Wizard',
      category: 'Microscopy',
      screenshot: '',
      uc2_verified: false,
      version: '1.0.0',
      createdAt: new Date().toISOString(),
      collection: ['Microscopy', 'FRAME'],
      notification: '',
      metadata: {
        version: '1.0',
        created: new Date().toISOString(),
        software: 'OpenUC2 OptiKit FRAME Wizard',
      },
    };

    const encoded = btoa(JSON.stringify(layout));
    window.location.href = `/configurator/?data=${encoded}`;
  }, [getSelectedComponents]);

  const stepPrice = getStepPrice(currentStep);
  const totalPrice = getTotalPrice();

  const renderStep = () => {
    switch (currentStep) {
      case 0: return <ObjectiveChangerStep />;
      case 1: return <ObjectiveStep />;
      case 2: return <IlluminationStep />;
      case 3: return <FluorescenceStep />;
      case 4: return <CameraStep />;
      case 5: return <SampleHolderStep />;
      case 6: return <SummaryQuoteStep onOpenInEditor={handleOpenInCanvas} />;
      default: return null;
    }
  };

  if (isLoading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
        <CircularProgress size={60} />
        <Typography sx={{ ml: 2 }} variant="h6">Loading FRAME libraries...</Typography>
      </Box>
    );
  }

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', height: '100vh', bgcolor: '#f5f5f5' }}>
      {/* Header */}
      <Paper
        elevation={2}
        sx={{
          p: 2,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          borderRadius: 0,
          bgcolor: '#1e4670',
          color: 'white',
        }}
      >
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
          <img
            src="/configurator/icons/uc2-frame.svg"
            alt="UC2 FRAME"
            style={{ height: 40, filter: 'brightness(0) invert(1)' }}
          />
          <Box>
            <Typography variant="h5" fontWeight="bold">
              UC2 FRAME Configurator
            </Typography>
            <Typography variant="body2" sx={{ opacity: 0.8 }}>
              Build your custom microscope step by step
            </Typography>
          </Box>
        </Box>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <Chip
            icon={<ShoppingCart />}
            label={`Total: $${totalPrice.toLocaleString()}`}
            sx={{ bgcolor: '#fff', color: '#1e4670', fontWeight: 'bold', fontSize: '1rem', p: 1 }}
          />
          <Tooltip title="Load preconfigured preset">
            <Button
              variant="outlined"
              onClick={() => setPresetOpen(true)}
              sx={{ color: 'white', borderColor: 'rgba(255,255,255,0.5)' }}
              startIcon={<Bookmark />}
              size="small"
            >
              Load Preset
            </Button>
          </Tooltip>
          <Tooltip title="Reset wizard">
            <Button
              variant="outlined"
              onClick={resetWizard}
              sx={{ color: 'white', borderColor: 'rgba(255,255,255,0.5)' }}
              startIcon={<Refresh />}
              size="small"
            >
              Reset
            </Button>
          </Tooltip>
        </Box>
      </Paper>

      {/* Stepper */}
      <Paper elevation={1} sx={{ px: 2, py: 1, borderRadius: 0 }}>
        <Stepper nonLinear activeStep={currentStep} alternativeLabel>
          {STEP_LABELS.map((label, index) => (
            <Step key={label} completed={index < currentStep}>
              <StepButton onClick={() => setStep(index)}>
                <StepLabel>{label}</StepLabel>
              </StepButton>
            </Step>
          ))}
        </Stepper>
      </Paper>

      {/* Main Content Area */}
      <Box sx={{ flex: 1, display: 'flex', overflow: 'hidden', p: 2, gap: 2 }}>
        {/* Left: Wizard Step */}
        <Paper
          elevation={2}
          sx={{
            flex: 1,
            p: 3,
            overflow: 'auto',
            display: 'flex',
            flexDirection: 'column',
          }}
        >
          {stepPrice > 0 && (
            <Chip
              label={`This step: +$${stepPrice.toLocaleString()}`}
              color="primary"
              variant="outlined"
              sx={{ alignSelf: 'flex-end', mb: 1 }}
            />
          )}
          {renderStep()}
        </Paper>

        {/* Right: Frame Preview */}
        <Paper elevation={2} sx={{ width: 400, minWidth: 350, overflow: 'auto' }}>
          <FramePreview />
        </Paper>
      </Box>

      {/* Footer Navigation */}
      <Paper
        elevation={3}
        sx={{
          p: 2,
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          borderRadius: 0,
        }}
      >
        <Button
          variant="outlined"
          startIcon={<ArrowBack />}
          onClick={prevStep}
          disabled={currentStep === 0}
        >
          Previous
        </Button>
        <Typography variant="body2" color="text.secondary">
          Step {currentStep + 1} of {TOTAL_STEPS}
        </Typography>
        {currentStep === TOTAL_STEPS - 1 ? (
          <Button
            variant="contained"
            color="success"
            startIcon={<ShoppingCart />}
            onClick={handleOpenInCanvas}
          >
            Open in Editor
          </Button>
        ) : (
          <Button variant="contained" endIcon={<ArrowForward />} onClick={nextStep}>
            Next
          </Button>
        )}
      </Paper>

      <PresetSelector open={presetOpen} onClose={() => setPresetOpen(false)} />
    </Box>
  );
}
