#!/usr/bin/env python3
"""
Fix GLB files exported from Open CASCADE / cascadio.

glTF standard uses metres; the Three.js scene in OptiKit uses mm (1 unit = 1 mm).
This script inserts a wrapper root node with scale [1000, 1000, 1000] into each
Open-CASCADE-origin GLB so the geometry fits the mm world without touching any
binary buffer data.

Usage
-----
# Fix all Open CASCADE GLBs in a folder (default: public/dev-glbs):
    python scripts/fix_glb_scale.py

# Explicit folder:
    python scripts/fix_glb_scale.py path/to/folder

# Dry-run (show what would change without writing):
    python scripts/fix_glb_scale.py --dry-run

# Also fix GLBs that don't have an Open CASCADE generator tag:
    python scripts/fix_glb_scale.py --all
"""

import argparse
import json
import struct
import sys
from pathlib import Path


def glb_apply_mm_scale(glb_path: Path, scale: float = 1000.0, dry_run: bool = False) -> bool:
    """
    Insert a __mm_scale__ wrapper node in the GLB root with the given scale.
    Returns True if the file was (or would be) modified, False if skipped.
    """
    data = glb_path.read_bytes()

    # Validate GLB header
    if len(data) < 28:
        print(f"  [skip]  {glb_path.name} — file too short")
        return False
    magic, _ver, _tot = struct.unpack_from('<III', data, 0)
    if magic != 0x46546C67:  # 'glTF'
        print(f"  [skip]  {glb_path.name} — not a GLB file")
        return False

    json_len, json_type = struct.unpack_from('<II', data, 12)
    if json_type != 0x4E4F534A:  # 'JSON'
        print(f"  [skip]  {glb_path.name} — first chunk is not JSON")
        return False

    gltf = json.loads(data[20:20 + json_len].rstrip(b' \x00'))

    # Already patched?
    nodes = gltf.get('nodes', [])
    if any(n.get('name') == '__mm_scale__' for n in nodes):
        print(f"  [skip]  {glb_path.name} — already patched")
        return False

    scene_idx = gltf.get('scene', 0)
    scene = gltf['scenes'][scene_idx]
    old_roots = scene.get('nodes', [])
    if not old_roots:
        print(f"  [skip]  {glb_path.name} — no root nodes in scene")
        return False

    # Inject wrapper
    wrapper = {
        'name': '__mm_scale__',
        'scale': [scale, scale, scale],
        'children': old_roots,
    }
    nodes.append(wrapper)
    gltf['nodes'] = nodes
    scene['nodes'] = [len(nodes) - 1]

    new_json = json.dumps(gltf, separators=(',', ':')).encode('utf-8')
    pad = (4 - len(new_json) % 4) % 4
    new_json_padded = new_json + b' ' * pad

    bin_chunk = data[12 + 8 + json_len:]  # BIN chunk stays untouched
    new_total = 12 + 8 + len(new_json_padded) + len(bin_chunk)

    if dry_run:
        print(f"  [dry]   {glb_path.name}  ({len(data)} → {new_total} bytes)")
        return True

    out = struct.pack('<III', 0x46546C67, 2, new_total)
    out += struct.pack('<II', len(new_json_padded), 0x4E4F534A)
    out += new_json_padded + bin_chunk
    glb_path.write_bytes(out)
    print(f"  [ok]    {glb_path.name}  ({len(data)} → {new_total} bytes)")
    return True


def is_opencascade_origin(glb_path: Path) -> bool:
    """Return True if the GLB was generated by Open CASCADE Technology."""
    try:
        data = glb_path.read_bytes()
        json_len, _ = struct.unpack_from('<II', data, 12)
        header = data[20:20 + json_len].rstrip(b' \x00').decode('utf-8', errors='replace')
        asset = json.loads(header).get('asset', {})
        gen = asset.get('generator', '').lower()
        return 'open cascade' in gen or 'opencascade' in gen
    except Exception:
        return False


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('folder', nargs='?', default='public/dev-glbs',
                        type=Path, help='Folder containing GLB files')
    parser.add_argument('--scale', type=float, default=1000.0,
                        help='Scale factor (default 1000 for metres→mm)')
    parser.add_argument('--all', action='store_true',
                        help='Fix all GLBs, not just Open CASCADE ones')
    parser.add_argument('--dry-run', action='store_true',
                        help='Show what would happen without writing')
    args = parser.parse_args()

    folder = args.folder.resolve()
    if not folder.is_dir():
        sys.exit(f"Not a directory: {folder}")

    glb_files = sorted(folder.glob('*.glb'))
    if not glb_files:
        print(f"No .glb files found in {folder}")
        return

    print(f"Folder : {folder}")
    print(f"Scale  : ×{args.scale}  ({'metres → mm' if args.scale == 1000 else 'custom'})")
    print(f"Mode   : {'dry-run' if args.dry_run else 'write'}\n")

    patched, skipped = 0, 0
    for p in glb_files:
        if args.all or is_opencascade_origin(p):
            changed = glb_apply_mm_scale(p, scale=args.scale, dry_run=args.dry_run)
            patched += int(changed)
        else:
            print(f"  [skip]  {p.name} — not Open CASCADE (use --all to force)")
            skipped += 1

    print(f"\nDone: {patched} patched, {skipped} skipped.")


if __name__ == '__main__':
    main()
